"""FRED dataset loader (Prophesee EVK4 HD HDF5 + coordinates.txt).

FRED ships event data as HDF5 files generated by Prophesee Metavision tools.
The exact internal layout is not documented in the FRED README, so this
loader tries the four layouts that Metavision (and forks) are known to
emit, in order:

  1. `/CD/events` as a structured dataset with named fields {x, y, p, t}.
  2. `/events`    as a structured dataset with named fields {x, y, p, t}.
  3. `/events`    as a group containing scalar datasets /events/{x,y,t,p}.
  4. Root-level scalar datasets {x, y, t, p}.

All four are recognized — if FRED is published with a different layout,
add a strategy in `_extract_events_from_h5`.

Annotations are read from `coordinates.txt`, one line per box:

    <time_seconds>: x1, y1, x2, y2, track_id, class_name

Polarity is left as the source convention (typically {0, 1}). Downstream
the `EventPreprocessor` normalizes it to {-1, +1} automatically.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import NamedTuple

import numpy as np


FRED_DEFAULT_RESOLUTION = (1280, 720)
"""Prophesee EVK4 HD resolution that FRED was recorded with."""


class FREDAnnotation(NamedTuple):
    """One bounding-box annotation from FRED's coordinates.txt."""

    t_us: int
    bbox: tuple[int, int, int, int]
    track_id: int
    class_name: str


def load_fred_events(
    path: str | Path,
    max_events: int | None = None,
    time_range_us: tuple[int, int] | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Load (x, y, t, p) arrays from a FRED HDF5 event file.

    Args:
        path: Path to .h5 / .hdf5 file.
        max_events: Optional cap. Events are random-subsampled (then
            re-sorted by time) to stay temporally consistent.
        time_range_us: Optional (t_start_us, t_end_us) slice applied
            after the file's own reference frame (t is NOT rezeroed —
            the caller can do that).

    Returns:
        (x, y, t, p) numpy arrays:
            x: int64 pixel x
            y: int64 pixel y
            t: int64 timestamps in microseconds (source reference frame)
            p: int64 polarity (typically {0, 1}, normalized by
               EventPreprocessor downstream)
    """
    try:
        import h5py
    except ImportError as e:
        raise ImportError(
            "h5py is required to load FRED HDF5 files. "
            "Install via `uv sync` or `pip install h5py`."
        ) from e

    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"FRED HDF5 not found: {path}")

    with h5py.File(str(path), "r") as f:
        x, y, t, p = _extract_events_from_h5(f)

    if time_range_us is not None:
        t0, t1 = time_range_us
        mask = (t >= int(t0)) & (t < int(t1))
        x, y, t, p = x[mask], y[mask], t[mask], p[mask]

    if max_events is not None and len(x) > max_events:
        rng = np.random.default_rng(0)
        sel = rng.choice(len(x), int(max_events), replace=False)
        sel.sort()
        x, y, t, p = x[sel], y[sel], t[sel], p[sel]

    return x, y, t, p


def _extract_events_from_h5(f) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Probe the HDF5 file for one of the known Prophesee event layouts."""
    if "CD" in f and "events" in f["CD"]:
        cd_events = f["CD"]["events"]
        out = _read_structured(cd_events)
        if out is not None:
            return out

    if "events" in f:
        events = f["events"]
        out = _read_structured(events)
        if out is not None:
            return out
        if hasattr(events, "keys"):
            keys = set(events.keys())
            if {"x", "y", "t", "p"}.issubset(keys):
                return (
                    np.asarray(events["x"][:], dtype=np.int64),
                    np.asarray(events["y"][:], dtype=np.int64),
                    np.asarray(events["t"][:], dtype=np.int64),
                    np.asarray(events["p"][:], dtype=np.int64),
                )

    root_keys = set(f.keys())
    if {"x", "y", "t", "p"}.issubset(root_keys):
        return (
            np.asarray(f["x"][:], dtype=np.int64),
            np.asarray(f["y"][:], dtype=np.int64),
            np.asarray(f["t"][:], dtype=np.int64),
            np.asarray(f["p"][:], dtype=np.int64),
        )

    raise ValueError(
        f"Could not locate events in HDF5 file. Root keys: {sorted(root_keys)}. "
        "Expected one of: /CD/events (structured), /events (structured or "
        "group), or root-level {x, y, t, p} datasets."
    )


def _read_structured(dataset) -> tuple[np.ndarray, ...] | None:
    """Return (x, y, t, p) if `dataset` is a structured array with those fields."""
    dtype = getattr(dataset, "dtype", None)
    if dtype is None or not getattr(dtype, "names", None):
        return None
    fields = set(dtype.names)
    if not {"x", "y", "t", "p"}.issubset(fields):
        return None
    data = dataset[:]
    return (
        data["x"].astype(np.int64),
        data["y"].astype(np.int64),
        data["t"].astype(np.int64),
        data["p"].astype(np.int64),
    )


_ANNOTATION_RE = re.compile(
    r"^\s*([\d.]+)\s*:\s*"
    r"(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*"
    r"(-?\d+)\s*,\s*(.+?)\s*$"
)


def load_fred_annotations(path: str | Path) -> list[FREDAnnotation]:
    """Read FRED's coordinates.txt annotation file.

    Lines have the form

        <time_seconds_float>: x1, y1, x2, y2, track_id, class_name

    Blank lines and lines beginning with `#` are skipped. Lines that
    do not match the expected pattern are silently ignored.

    Args:
        path: Path to coordinates.txt (or coordinates_rgb.txt).

    Returns:
        List of `FREDAnnotation` tuples sorted by timestamp.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"FRED annotation file not found: {path}")

    annotations: list[FREDAnnotation] = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            m = _ANNOTATION_RE.match(line)
            if not m:
                continue
            t_sec, x1, y1, x2, y2, tid, cname = m.groups()
            annotations.append(
                FREDAnnotation(
                    t_us=int(round(float(t_sec) * 1_000_000)),
                    bbox=(int(x1), int(y1), int(x2), int(y2)),
                    track_id=int(tid),
                    class_name=cname.strip(),
                )
            )
    annotations.sort(key=lambda a: a.t_us)
    return annotations


def annotations_in_window(
    annotations: list[FREDAnnotation],
    t_start_us: int,
    t_end_us: int,
) -> list[FREDAnnotation]:
    """Slice annotations to those whose timestamp lies in [t_start, t_end)."""
    return [a for a in annotations if t_start_us <= a.t_us < t_end_us]
